RODOS: RODOS::BlockFifo< Type, len > Class Template Reference
RODOS::BlockFifo< Type, len > Class Template Reference
#include <fifo.h>
Public Member Functions
BlockFifo ()
Type * getBufferToWrite (int &maxLen)
returns pointer to write and maximal number of entries you may write
void writeConcluded (int numOfWrittenElements)
call this after you have written in the buffer you got from getBufferToWrite
Type * getBufferToRead (int &maxLen)
void readConcluded (int sizeRed)
call this after you have read in the buffer you got from getBufferToRead
Protected Member Functions
int advanceIndexEx (int index, int advanceSize)
Detailed Description
template<class Type, int len>
class RODOS::BlockFifo< Type, len >
A Fifo that lets you write or read continius Blocks of the stored type. Gives out pointers to the internal space, so you can copy data directly from/to there. Useful for DMA trasnfers.
Definition at line 323 of file fifo.h.
Constructor & Destructor Documentation
template<class Type , int len> RODOS::BlockFifo< Type, len >::BlockFifo () [inline]
Definition at line 335 of file fifo.h.
Member Function Documentation
template<class Type , int len> int RODOS::BlockFifo< Type, len >::advanceIndexEx (int index, int advanceSize) [inline, protected]
Definition at line 325 of file fifo.h.
Referenced by RODOS::BlockFifo< Type, len >::readConcluded(), and RODOS::BlockFifo< Type, len >::writeConcluded().
template<class Type , int len> Type* RODOS::BlockFifo< Type, len >::getBufferToRead (int & maxLen) [inline]
Definition at line 363 of file fifo.h.
References RODOS::Fifo< Type, len >::buffer, RODOS::Fifo< Type, len >::readX, and RODOS::Fifo< Type, len >::writeX.
template<class Type , int len> Type* RODOS::BlockFifo< Type, len >::getBufferToWrite (int & maxLen) [inline]
returns pointer to write and maximal number of entries you may write
Definition at line 339 of file fifo.h.
References RODOS::Fifo< Type, len >::advanceIndex(), RODOS::Fifo< Type, len >::buffer, RODOS::Fifo< Type, len >::readX, and RODOS::Fifo< Type, len >::writeX.
template<class Type , int len> void RODOS::BlockFifo< Type, len >::readConcluded (int sizeRed) [inline]
call this after you have read in the buffer you got from getBufferToRead
Definition at line 381 of file fifo.h.
References RODOS::BlockFifo< Type, len >::advanceIndexEx(), and RODOS::Fifo< Type, len >::readX.
template<class Type , int len> void RODOS::BlockFifo< Type, len >::writeConcluded (int numOfWrittenElements) [inline]
call this after you have written in the buffer you got from getBufferToWrite
Definition at line 358 of file fifo.h.
References RODOS::BlockFifo< Type, len >::advanceIndexEx(), and RODOS::Fifo< Type, len >::writeX.
The documentation for this class was generated from the following file:
/home/sem40wk/workarea/rodos/rodos-113/api/fifo.h