RODOS: RODOS::TopicListReport Class Reference
RODOS::TopicListReport Class Reference
#include <networkmessage.h>
Public Member Functions
TopicListReport ()
Constructor, initializes topicList.
void init ()
bool find (const short topicId) const
void add (const short topicId)
int numberOfBytesToSend ()
returns the size needed for transmission
Public Attributes
int32_t numberOfTopics
total number of topics assigned for the network
int16_t topicList [MAX_SUBSCRIBERS]
simple list of topic IDs subscribed for network
Detailed Description
Definition at line 140 of file networkmessage.h.
Constructor & Destructor Documentation
RODOS::TopicListReport::TopicListReport () [inline]
Constructor, initializes topicList.
Definition at line 145 of file networkmessage.h.
Member Function Documentation
void RODOS::TopicListReport::add (const short topicId) [inline]
Adds a new topic to list, if not already present.
Parameters:
[in] topicId ID to add to the list
Definition at line 163 of file networkmessage.h.
bool RODOS::TopicListReport::find (const short topicId) const [inline]
Look up list, whether a topic is set for network messages.
Parameters:
[in] topicId ID to check whether topic is listed
Definition at line 151 of file networkmessage.h.
Referenced by operator=(), and RODOS::Gateway::shouldTopicForwarded().
void RODOS::TopicListReport::init (void) [inline]
Definition at line 146 of file networkmessage.h.
Referenced by put_len().
int RODOS::TopicListReport::numberOfBytesToSend () [inline]
returns the size needed for transmission
Definition at line 176 of file networkmessage.h.
References topicList.
Member Data Documentation
int32_t RODOS::TopicListReport::numberOfTopics
total number of topics assigned for the network
Definition at line 142 of file networkmessage.h.
Referenced by operator=(), and put_END_OR_HEADER().
int16_t RODOS::TopicListReport::topicList[MAX_SUBSCRIBERS]
simple list of topic IDs subscribed for network
Definition at line 143 of file networkmessage.h.
Referenced by numberOfBytesToSend(), and operator=().
The documentation for this class was generated from the following file:
/home/sem40wk/workarea/rodos/rodos-113/api/gateway/networkmessage.h