RODOS: RODOS::SubscriberReceiver< Type > Class Template Reference
RODOS::SubscriberReceiver< Type > Class Template Reference
#include <subscriber.h>
Public Member Functions
SubscriberReceiver (TopicInterface &topic, const char *name="anonymSubscriber")
SubscriberReceiver (TopicInterface &topic, void(*funcPtr)(Type &), const char *name="anonymSubscriber")
virtual void put (Type &msg)
virtual void put (Type &msg, const NetMsgInfo &netMsgInfo)
long put (const long topicId, const long len, const void *data, const NetMsgInfo &netMsgInfo)
Default function: forward the message and invoke the receiver (putter). It locks the semaphore protector.
Private Attributes
void(* receiver)(Type &msg)
Reference to the associated handler of a message received.
Detailed Description
template<class Type>
class RODOS::SubscriberReceiver< Type >
Simple Subscriver interface for userd
Definition at line 172 of file subscriber.h.
Constructor & Destructor Documentation
template<class Type > RODOS::SubscriberReceiver< Type >::SubscriberReceiver (TopicInterface & topic, const char * name = "anonymSubscriber") [inline]
Definition at line 176 of file subscriber.h.
References RODOS::SubscriberReceiver< Type >::receiver.
template<class Type > RODOS::SubscriberReceiver< Type >::SubscriberReceiver (TopicInterface & topic, void(*)(Type &) funcPtr, const char * name = "anonymSubscriber") [inline]
Definition at line 180 of file subscriber.h.
References RODOS::SubscriberReceiver< Type >::receiver.
Member Function Documentation
template<class Type > virtual void RODOS::SubscriberReceiver< Type >::put (Type & msg) [inline, virtual]
Definition at line 185 of file subscriber.h.
References RODOS::SubscriberReceiver< Type >::receiver.
Referenced by RODOS::SubscriberReceiver< Type >::put().
template<class Type > long RODOS::SubscriberReceiver< Type >::put (const long topicId, const long len, const void * data, const NetMsgInfo & netMsgInfo) [inline, virtual]
Default function: forward the message and invoke the receiver (putter). It locks the semaphore protector.
Reimplemented from RODOS::Subscriber.
Definition at line 187 of file subscriber.h.
References RODOS::SubscriberReceiver< Type >::put().
template<class Type > virtual void RODOS::SubscriberReceiver< Type >::put (Type & msg, const NetMsgInfo & netMsgInfo) [inline, virtual]
Definition at line 186 of file subscriber.h.
References RODOS::SubscriberReceiver< Type >::put().
Referenced by RODOS::SubscriberReceiver< Type >::put().
Member Data Documentation
template<class Type > void(* RODOS::SubscriberReceiver< Type >::receiver)(Type &msg) [private]
Reference to the associated handler of a message received.
Reimplemented from RODOS::Subscriber.
Definition at line 173 of file subscriber.h.
Referenced by RODOS::SubscriberReceiver< Type >::put(), and RODOS::SubscriberReceiver< Type >::SubscriberReceiver().
The documentation for this class was generated from the following file:
/home/sem40wk/workarea/rodos/rodos-113/api/subscriber.h