RODOS: RODOS::SyncFifo< Type, len > Class Template Reference
RODOS::SyncFifo< Type, len > Class Template Reference
A synchronized fifo.
#include <fifo.h>
Public Member Functions
SyncFifo ()
bool putGeneric (const long topicId, const unsigned int msgLen, const void *msg, const NetMsgInfo &netMsgInfo)
bool syncPut (Type &val, const int64_t timeout=0)
int syncGet (Type &val, const int64_t timeout=0)
Protected Attributes
Thread * suspendedReader
Thread * suspendedWriter
Detailed Description
template<class Type, int len>
class RODOS::SyncFifo< Type, len >
A synchronized fifo.
Like Fifo, but it provides syncPut which block if the fifo is full and syncRead which block if the fifo is empty. Each function may have a timeout. If no timeout is given, or timeout == 0 it will wait util the fifo is not empty/full. Warning: Only for one writer and one reader. If more than that is required it has to be protected using semaphores.
Definition at line 154 of file fifo.h.
Constructor & Destructor Documentation
template<class Type , int len> RODOS::SyncFifo< Type, len >::SyncFifo () [inline]
Definition at line 162 of file fifo.h.
References RODOS::SyncFifo< Type, len >::suspendedReader, and RODOS::SyncFifo< Type, len >::suspendedWriter.
Member Function Documentation
template<class Type , int len> bool RODOS::SyncFifo< Type, len >::putGeneric (const long topicId, const unsigned int msgLen, const void * msg, const NetMsgInfo & netMsgInfo) [inline, virtual]
Implements the generic interface of putter: Warning does not suspends if fifo full
Reimplemented from RODOS::Fifo< Type, len >.
Definition at line 172 of file fifo.h.
References RODOS::ERROR(), RODOS::Fifo< Type, len >::put(), RODOS::Thread::resume(), and RODOS::SyncFifo< Type, len >::suspendedReader.
template<class Type , int len> int RODOS::SyncFifo< Type, len >::syncGet (Type & val, const int64_t timeout = 0) [inline]
return true == ok, false = fifo empty, val not modified
Definition at line 216 of file fifo.h.
References END_OF_TIME, RODOS::Thread::getCurrentThread(), NOW, RODOS::Thread::resume(), RODOS::Thread::suspendCallerUntil(), RODOS::SyncFifo< Type, len >::suspendedReader, and RODOS::SyncFifo< Type, len >::suspendedWriter.
template<class Type , int len> bool RODOS::SyncFifo< Type, len >::syncPut (Type & val, const int64_t timeout = 0) [inline]
suspends while fifo is full. returns true == ok, false == timeout,
Definition at line 188 of file fifo.h.
References END_OF_TIME, RODOS::Thread::getCurrentThread(), NOW, RODOS::Fifo< Type, len >::put(), RODOS::Thread::resume(), RODOS::Thread::suspendCallerUntil(), RODOS::SyncFifo< Type, len >::suspendedReader, and RODOS::SyncFifo< Type, len >::suspendedWriter.
Member Data Documentation
template<class Type , int len> Thread* RODOS::SyncFifo< Type, len >::suspendedReader [protected]
Definition at line 157 of file fifo.h.
Referenced by RODOS::SyncFifo< Type, len >::putGeneric(), RODOS::SyncFifo< Type, len >::SyncFifo(), RODOS::SyncFifo< Type, len >::syncGet(), and RODOS::SyncFifo< Type, len >::syncPut().
template<class Type , int len> Thread* RODOS::SyncFifo< Type, len >::suspendedWriter [protected]
Definition at line 158 of file fifo.h.
Referenced by RODOS::SyncFifo< Type, len >::SyncFifo(), RODOS::SyncFifo< Type, len >::syncGet(), and RODOS::SyncFifo< Type, len >::syncPut().
The documentation for this class was generated from the following file:
/home/sem40wk/workarea/rodos/rodos-113/api/fifo.h