RODOS: RODOS::Topic< Type > Class Template Reference
RODOS::Topic< Type > Class Template Reference
Topic to patch publisher and subscribers.
#include <topic.h>
Public Member Functions
Topic (long id, const char *name)
~Topic ()
unsigned long publish (Type &msg, bool shallSendToNetwork=true)
unsigned long publishConst (Type msgConst, bool shallSendToNetwork=true)
unsigned long publishMsgPart (Type &msg, unsigned int lenToSend, bool shallSendToNetwork=true)
unsigned long requestLocal (Type &msg)
Detailed Description
template<class Type>
class RODOS::Topic< Type >
Topic to patch publisher and subscribers.
The middleware communication is based on the publisher/subscriber protocol. Publishers make messages public under a given topic. Subscriber to a given topic get all messages which are published under the given topic. To establish a transfer path, both, publisher and subscriber have to share the same topic.
A Topic consists of a pair: a data-type and an integer representing the topic identifier.
Topic provides methods to publish and distribute messages.
The current implementation accepts only shorts as topicId because of limitations on the FPGA (Hardware) Middleware implementation.
topic id 0 is reserved for middleware messages (eg. topic lists) if you use topic id -1 the system will generate an id according to the name used in the constructor. This number will be compatible with all hardware implementations. We recommend to use this feature. This is compatible with our hardware networks.
Definition at line 179 of file topic.h.
Constructor & Destructor Documentation
template<class Type> RODOS::Topic< Type >::Topic (long id, const char * name) [inline]
constructor, parameter name is used for debug purposes and as hash value to generate a topic id if it was defined as -1. This is the proposed method.
Definition at line 186 of file topic.h.
template<class Type> RODOS::Topic< Type >::~Topic () [inline]
Definition at line 188 of file topic.h.
Member Function Documentation
template<class Type> unsigned long RODOS::Topic< Type >::publish (Type & msg, bool shallSendToNetwork = true) [inline]
publish/distribute the message to all listeners to the given serviceId. if shallSendToNetwork the message will be fordarded to gateways too (default) warning 1: Never use it from an interrupt server. warning 2: the pointer to msg will be distributed. A Subscriber may modify its content
Definition at line 197 of file topic.h.
Referenced by RODOS::Topic< GenericMsgRef >::publish(), RODOS::Topic< GenericMsgRef >::publishConst(), and RODOS::Topic< GenericMsgRef >::requestLocal().
template<class Type> unsigned long RODOS::Topic< Type >::publishConst (Type msgConst, bool shallSendToNetwork = true) [inline]
To publish constants, But please only for basic data types (char, short, long, float, double)
Definition at line 204 of file topic.h.
template<class Type> unsigned long RODOS::Topic< Type >::publishMsgPart (Type & msg, unsigned int lenToSend, bool shallSendToNetwork = true) [inline]
To send only a part of the data type, and not the whole object. for example for strings warning: Never us it from an interrupt server.
Definition at line 214 of file topic.h.
Referenced by RODOS::Topic< GenericMsgRef >::publishMsgPart().
template<class Type> unsigned long RODOS::Topic< Type >::requestLocal (Type & msg) [inline]
request is like publish, but the calles expects data back instead of sending it. The internal mechanims is identical the same like publisch, the middleware will call puuters from subscribers. Such puters shall proivde data instad of geting it.
Definition at line 223 of file topic.h.
The documentation for this class was generated from the following file:
/home/sem40wk/workarea/rodos/rodos-113/api/topic.h