RODOS: RODOS::Thread Class Reference
RODOS::Thread Class Reference
Thread provides stack and context management
#include <thread.h>
Public Member Functions
Thread (const char *name="AnonymThread", const long priority=DEFAULT_THREAD_PRIORITY, const long stackSize=DEFAULT_STACKSIZE)
virtual ~Thread ()
Destructor.
virtual void run ()=0
virtual void init ()
long getPriority () const
void setPriority (const long prio)
void suspendUntilNextBeat ()
void setPeriodicBeat (const TTime begin, const TTime period)
void resume ()
void resumeAndYield ()
Static Public Member Functions
static void startAllThreads ()
if required (only on gast OSs) called by scheduler
static bool suspendCallerUntil (const TTime reactivationTime=END_OF_TIME, void *signaler=0)
static void yield ()
static Thread * getCurrentThread ()
static Thread * findNextToRun (TTime timeNow)
static Thread * findNextWaitingFor (void *signaler)
static unsigned long long getScheduleCounter ()
static long setPrioCurrentRunner (long newPrio)
Private Member Functions
void create ()
called in main() after all constuctors, to create/init thread
void activate ()
continue the execution of the thread
Static Private Member Functions
static void initializeThreads ()
call the init method of all threads
Private Attributes
long stackSize
size of the thread's stack in bytes
long * stack
pointer to the thread's stack (beginn high growing low)
char * stackBegin
stack growns down, this is the lower limit
volatile long * context
pointer to stored context
volatile long priority
volatile TTime suspendedUntil
void * waitingFor
TTime nextBeat
the next time to awake (used in wait)
TTime period
To repeate every period localTime units.
volatile unsigned long long lastActivation
used by scheduling algorithm
Static Private Attributes
static List threadList
List of all threads.
static Thread * currentThread
pointer to currently running thread
Friends
class Scheduler
class ThreadChecker
void schedulerWrapper (long *ctx)
void threadStartupWrapper (Thread *)
void initSystem ()
void startIdleThread ()
Detailed Description
Thread provides stack and context management
Definition at line 72 of file thread.h.
Constructor & Destructor Documentation
RODOS::Thread::Thread (const char * name = "AnonymThread", const long priority = DEFAULT_THREAD_PRIORITY, const long stackSize = DEFAULT_STACKSIZE)
Initialization of the thread. A user should use a meaningful name for the thread.
Parameters:
name Name of the thread.
priority The priority for the thread. Only the thread with the highest value from several runnable threads at a time get computing resources.
stackSize The size of the stack memory for the thread. Choice a matching value for the task of the thread.
See also:
DEFAULT_THREAD_PRIORITY
DEFAULT_STACKSIZE
virtual RODOS::Thread::~Thread () [virtual]
Destructor.
Member Function Documentation
void RODOS::Thread::activate () [private]
continue the execution of the thread
void RODOS::Thread::create () [private]
called in main() after all constuctors, to create/init thread
static Thread* RODOS::Thread::findNextToRun (TTime timeNow) [static]
Search over all threads and select the one with the highest priority which is ready to run
Returns:
The pointer to the highest priorized runnable thread.
See also:
resume
static Thread* RODOS::Thread::findNextWaitingFor (void * signaler) [static]
Search over all threads and select the one with the highest priority which is not ready to run and waiting for the given signaler.
Parameters:
signaler Pointer to the signaler where the thread has to wait on.
Returns:
Pointer to the highest priorized thread waiting on the signaler.
static Thread* RODOS::Thread::getCurrentThread () [static]
Get a pointer to the currently running thread. The method can used to identify the calling thread in classes with no inheritance to the class Thread.
Returns:
Pointer to the currently running thread.
Referenced by RODOS::SyncFifo< Type, len >::syncGet(), and RODOS::SyncFifo< Type, len >::syncPut().
long RODOS::Thread::getPriority () const
Get priority of thread.
Returns:
The priority of the thread.
static unsigned long long RODOS::Thread::getScheduleCounter () [static]
Get the schedule counter.
Returns:
The current schedule counter. The counter is increased for each schedule operation.
virtual void RODOS::Thread::init (void) [inline, virtual]
The method is called after all constructors are executed and before the threads are activated by a call to the method run.
It should be overloaded in case the thread has to call other objects for the initialization, hence after all instances are present and before any run method is invoked.
See also:
run
Definition at line 144 of file thread.h.
static void RODOS::Thread::initializeThreads () [static, private]
call the init method of all threads
void RODOS::Thread::resume ()
Resume the thread. The tread get after the call to the method computing resources if no other thread with a higher priority occupy the resources. It end calls to the methods suspendCallerUntil and suspendUntilNextBeat.
See also:
suspendCallerUntil
suspendUntilNextBeat
Semaphore
Referenced by RODOS::SyncFifo< Type, len >::putGeneric(), resumeAndYield(), RODOS::SyncFifo< Type, len >::syncGet(), and RODOS::SyncFifo< Type, len >::syncPut().
void RODOS::Thread::resumeAndYield () [inline]
like resume, but if the resumed thread has a higher piroirty than the runing one then a task switch will take place at oncce.
WARNING: NEVER call it from an interrupt server
Definition at line 220 of file thread.h.
References resume(), and yield().
virtual void RODOS::Thread::run () [pure virtual]
Entry point for user code. The thread activities shall implement by overloading this method.
Implemented in RODOS::Gateway, and RODOS::TopicReporter.
void RODOS::Thread::setPeriodicBeat (const TTime begin, const TTime period)
Defines the start of computing periods for the method suspendUntilNextBeat.
Parameters:
begin Time for first the start time of the first computing period.
period Period between the start time of computing periods.
See also:
suspendUntilNextBeat
static long RODOS::Thread::setPrioCurrentRunner (long newPrio) [static]
Sets the priority of the currently running thread. Use it carefully.
Parameters:
newPrio Priority to set to the currently running thread.
Returns:
The previous priority of the currently running thread.
See also:
setPriority
void RODOS::Thread::setPriority (const long prio)
Set priority of thread
Parameters:
[in] prio The new priority of the thread.
static void RODOS::Thread::startAllThreads () [static]
if required (only on gast OSs) called by scheduler
static bool RODOS::Thread::suspendCallerUntil (const TTime reactivationTime = END_OF_TIME, void * signaler = 0) [static]
Suspend the thread until a given time or a wake up by a call to the method resume. By the optional pointer to a signaler the thread could be woken up. A signal is for example an object of type inherited from class Event.
Parameters:
[in] reactivationTime Optional time to wake up. Default value is end of time.
[in] signaler Pointer to signaler, which can resume the thread.
Returns:
True if the thread is resumed, false if the reactivation time is reached.
See also:
resume
Event
Referenced by RODOS::SyncFifo< Type, len >::syncGet(), and RODOS::SyncFifo< Type, len >::syncPut().
void RODOS::Thread::suspendUntilNextBeat ()
Suspend a thread until the next computing period of the thread start. The computing periods are computed from a start and a periodical time set with the method setPeriodicBeat. The thread is suspend for ever if setPeriodicBeat isn't called before a call to this method.
A call to method resume by another thread or an subscribed event or topic can wake up the thread before the next computing period starts. In this cases the reason shall checked by the thread after wake up.
See also:
setPeriodicBeat
resume
Subscriber
static void RODOS::Thread::yield () [static]
Cause the currently running thread to pause and perform a reschedule.
Referenced by resumeAndYield().
Friends And Related Function Documentation
void initSystem () [friend]
friend class Scheduler [friend]
Definition at line 77 of file thread.h.
void schedulerWrapper (long * ctx) [friend]
void startIdleThread () [friend]
friend class ThreadChecker [friend]
Definition at line 78 of file thread.h.
void threadStartupWrapper (Thread *) [friend]
Member Data Documentation
volatile long* RODOS::Thread::context [private]
pointer to stored context
Definition at line 85 of file thread.h.
Thread* RODOS::Thread::currentThread [static, private]
pointer to currently running thread
Definition at line 107 of file thread.h.
volatile unsigned long long RODOS::Thread::lastActivation [private]
used by scheduling algorithm
Definition at line 103 of file thread.h.
TTime RODOS::Thread::nextBeat [private]
the next time to awake (used in wait)
Definition at line 97 of file thread.h.
TTime RODOS::Thread::period [private]
To repeate every period localTime units.
Definition at line 98 of file thread.h.
volatile long RODOS::Thread::priority [private]
priority of thread, higher values are serverd first
Definition at line 89 of file thread.h.
long* RODOS::Thread::stack [private]
pointer to the thread's stack (beginn high growing low)
Definition at line 83 of file thread.h.
char* RODOS::Thread::stackBegin [private]
stack growns down, this is the lower limit
Definition at line 84 of file thread.h.
long RODOS::Thread::stackSize [private]
size of the thread's stack in bytes
Definition at line 82 of file thread.h.
volatile TTime RODOS::Thread::suspendedUntil [private]
It will be activated only after this time
Definition at line 92 of file thread.h.
List RODOS::Thread::threadList [static, private]
List of all threads.
Definition at line 81 of file thread.h.
void* RODOS::Thread::waitingFor [private]
if waiting for reactivation from someone, eg semaphore
Definition at line 95 of file thread.h.
The documentation for this class was generated from the following file:
/home/sem40wk/workarea/rodos/rodos-113/api/thread.h