RODOS: RODOS::TopicInterface Class Reference
RODOS::TopicInterface Class Reference
TopicInterface only for internal use.
#include <topic.h>
Public Member Functions
TopicInterface (long id, long len, const char *name)
virtual ~TopicInterface ()
unsigned long publish (void *msg, bool shallSendToNetwork=true, NetMsgInfo *netMsgInfo=0)
unsigned long publishMsgPart (void *msg, unsigned int lenToSend, bool shallSendToNetwork=true, NetMsgInfo *netMsgInfo=0)
void publishFromInterrupt (void *any, int len=0)
unsigned long requestLocal (void *msg)
Static Public Member Functions
static TopicInterface * findTopicId (long wantedTopicId)
return 0 it not found
Public Attributes
List mySubscribers
List of pointers to subscribers associated to one topic instance.
long topicId
Topic ID used for identification of the correct subscriber.
long msgLen
Size of message transfered via this topic.
Static Public Attributes
static List topicList
List of all topics present in the system.
Friends
class Gateway
class Subscriber
class TopicReporter
void initSystem ()
Detailed Description
TopicInterface only for internal use.
The middleware communication is based on the publisher/subscriber protocol. Publishers make messages public under a given topic. Subscriber to a given topic get all messages which are published under the given topic. To establish a transfer path, both, publisher and subscriber have to share the same topic.
A Topic is a pair: data-type and an integer representing a topic identifier.
To access topics in an generic way which is independent of data type and topicId, a TopicInterface is created.
Definition at line 83 of file topic.h.
Constructor & Destructor Documentation
RODOS::TopicInterface::TopicInterface (long id, long len, const char * name)
virtual RODOS::TopicInterface::~TopicInterface () [inline, virtual]
Definition at line 110 of file topic.h.
References RODOS::ERROR().
Member Function Documentation
static TopicInterface* RODOS::TopicInterface::findTopicId (long wantedTopicId) [static]
return 0 it not found
unsigned long RODOS::TopicInterface::publish (void * msg, bool shallSendToNetwork = true, NetMsgInfo * netMsgInfo = 0)
publish/distribute the message to all listeners to the given serviceId. if shallSendToNetwork the message will be forwarded to gateways too (default). warning 1: Never use it from an interrupt server. warning 2: the pointer to msg will be distributed. A Subscriber may modify its content
Referenced by requestLocal().
void RODOS::TopicInterface::publishFromInterrupt (void * any, int len = 0)
Publishfrom interrupts uses no semaphores as protection! the Subscriber shall use no thread operations the Subscriber shall be as short as possible
unsigned long RODOS::TopicInterface::publishMsgPart (void * msg, unsigned int lenToSend, bool shallSendToNetwork = true, NetMsgInfo * netMsgInfo = 0)
Usually we use the length of the corresponding data type associated to the topic but for some exceptional cases, like for strings, we may send shorter messages. warning 1: Never use it from an interrupt server. warning 2: the pointer to msg will be distributed. A Subscriber may modify its content
unsigned long RODOS::TopicInterface::requestLocal (void * msg) [inline]
request is like publish, but the calles expects data back instead of sending it. The internal mechanims is identical the same like publisch, the middleware will call puuters from subscribers. Such puters shall proivde data instad of geting it.
Definition at line 139 of file topic.h.
References publish().
Friends And Related Function Documentation
friend class Gateway [friend]
Definition at line 86 of file topic.h.
void initSystem () [friend]
friend class Subscriber [friend]
Definition at line 87 of file topic.h.
friend class TopicReporter [friend]
Definition at line 89 of file topic.h.
Member Data Documentation
long RODOS::TopicInterface::msgLen
Size of message transfered via this topic.
Definition at line 102 of file topic.h.
List RODOS::TopicInterface::mySubscribers
List of pointers to subscribers associated to one topic instance.
Definition at line 98 of file topic.h.
long RODOS::TopicInterface::topicId
Topic ID used for identification of the correct subscriber.
Definition at line 100 of file topic.h.
List RODOS::TopicInterface::topicList [static]
List of all topics present in the system.
Definition at line 96 of file topic.h.
The documentation for this class was generated from the following file:
/home/sem40wk/workarea/rodos/rodos-113/api/topic.h