RODOS: RODOS::MultipleReaderFifo< Type, len, numOfreaders > Class Template Reference
RODOS::MultipleReaderFifo< Type, len, numOfreaders > Class Template Reference
#include <fifo.h>
Public Member Functions
MultipleReaderFifo ()
int getReaderId ()
bool putGeneric (const long topicId, const unsigned int msgLen, const void *msg, const NetMsgInfo &netMsgInfo)
bool put (const Type &val)
bool get (Type &val, int readerId)
int getLen ()
Protected Member Functions
int advanceIndex (int index)
Protected Attributes
Type buffer [len]
volatile int writeX
volatile int readX [numOfreaders]
unsigned int readerCnt
used only to genereate readerId, if user wisches!
Detailed Description
template<typename Type, int len, int numOfreaders>
class RODOS::MultipleReaderFifo< Type, len, numOfreaders >
Definition at line 247 of file fifo.h.
Constructor & Destructor Documentation
template<typename Type , int len, int numOfreaders> RODOS::MultipleReaderFifo< Type, len, numOfreaders >::MultipleReaderFifo () [inline]
Definition at line 267 of file fifo.h.
References RODOS::MultipleReaderFifo< Type, len, numOfreaders >::readerCnt, RODOS::MultipleReaderFifo< Type, len, numOfreaders >::readX, and RODOS::MultipleReaderFifo< Type, len, numOfreaders >::writeX.
Member Function Documentation
template<typename Type , int len, int numOfreaders> int RODOS::MultipleReaderFifo< Type, len, numOfreaders >::advanceIndex (int index) [inline, protected]
advance index to next position with overflow to 0 to implement a ring
Definition at line 260 of file fifo.h.
Referenced by RODOS::MultipleReaderFifo< Type, len, numOfreaders >::get(), and RODOS::MultipleReaderFifo< Type, len, numOfreaders >::put().
template<typename Type , int len, int numOfreaders> bool RODOS::MultipleReaderFifo< Type, len, numOfreaders >::get (Type & val, int readerId) [inline]
return true == ok, false = fifo empty, val not modified
Definition at line 303 of file fifo.h.
References RODOS::MultipleReaderFifo< Type, len, numOfreaders >::advanceIndex(), RODOS::MultipleReaderFifo< Type, len, numOfreaders >::buffer, RODOS::MultipleReaderFifo< Type, len, numOfreaders >::readX, and RODOS::MultipleReaderFifo< Type, len, numOfreaders >::writeX.
template<typename Type , int len, int numOfreaders> int RODOS::MultipleReaderFifo< Type, len, numOfreaders >::getLen () [inline]
Definition at line 313 of file fifo.h.
template<typename Type , int len, int numOfreaders> int RODOS::MultipleReaderFifo< Type, len, numOfreaders >::getReaderId () [inline]
Definition at line 273 of file fifo.h.
References RODOS::MultipleReaderFifo< Type, len, numOfreaders >::readerCnt.
template<typename Type , int len, int numOfreaders> bool RODOS::MultipleReaderFifo< Type, len, numOfreaders >::put (const Type & val) [inline]
returns true == ok, false == fifo full
Definition at line 289 of file fifo.h.
References RODOS::MultipleReaderFifo< Type, len, numOfreaders >::advanceIndex(), RODOS::MultipleReaderFifo< Type, len, numOfreaders >::buffer, RODOS::MultipleReaderFifo< Type, len, numOfreaders >::readX, and RODOS::MultipleReaderFifo< Type, len, numOfreaders >::writeX.
Referenced by RODOS::MultipleReaderFifo< Type, len, numOfreaders >::putGeneric().
template<typename Type , int len, int numOfreaders> bool RODOS::MultipleReaderFifo< Type, len, numOfreaders >::putGeneric (const long topicId, const unsigned int msgLen, const void * msg, const NetMsgInfo & netMsgInfo) [inline, virtual]
implements the generic interface of putter
Reimplemented from RODOS::Putter.
Definition at line 280 of file fifo.h.
References RODOS::ERROR(), and RODOS::MultipleReaderFifo< Type, len, numOfreaders >::put().
Member Data Documentation
template<typename Type , int len, int numOfreaders> Type RODOS::MultipleReaderFifo< Type, len, numOfreaders >::buffer[len] [protected]
Definition at line 251 of file fifo.h.
Referenced by RODOS::MultipleReaderFifo< Type, len, numOfreaders >::get(), and RODOS::MultipleReaderFifo< Type, len, numOfreaders >::put().
template<typename Type , int len, int numOfreaders> unsigned int RODOS::MultipleReaderFifo< Type, len, numOfreaders >::readerCnt [protected]
used only to genereate readerId, if user wisches!
Definition at line 255 of file fifo.h.
Referenced by RODOS::MultipleReaderFifo< Type, len, numOfreaders >::getReaderId(), and RODOS::MultipleReaderFifo< Type, len, numOfreaders >::MultipleReaderFifo().
template<typename Type , int len, int numOfreaders> volatile int RODOS::MultipleReaderFifo< Type, len, numOfreaders >::readX[numOfreaders] [protected]
Definition at line 254 of file fifo.h.
Referenced by RODOS::MultipleReaderFifo< Type, len, numOfreaders >::get(), RODOS::MultipleReaderFifo< Type, len, numOfreaders >::MultipleReaderFifo(), and RODOS::MultipleReaderFifo< Type, len, numOfreaders >::put().
template<typename Type , int len, int numOfreaders> volatile int RODOS::MultipleReaderFifo< Type, len, numOfreaders >::writeX [protected]
Definition at line 253 of file fifo.h.
Referenced by RODOS::MultipleReaderFifo< Type, len, numOfreaders >::get(), RODOS::MultipleReaderFifo< Type, len, numOfreaders >::MultipleReaderFifo(), and RODOS::MultipleReaderFifo< Type, len, numOfreaders >::put().
The documentation for this class was generated from the following file:
/home/sem40wk/workarea/rodos/rodos-113/api/fifo.h