RODOS: RODOS::NetworkMessage Class Reference
RODOS::NetworkMessage Class Reference
#include <networkmessage.h>
Public Member Functions
void put_checkSum (uint16_t x)
void put_senderNode (int32_t x)
void put_sentTime (int64_t x)
void put_senderThreadId (uint32_t x)
void put_topicId (uint32_t x)
void put_maxStepsToForward (int16_t x)
void put_len (uint16_t x)
void put_END_OR_HEADER (int8_t x)
uint16_t get_checksum () const
int32_t get_senderNode () const
int64_t get_sentTime () const
uint32_t get_senderThreadId () const
uint32_t get_topicId () const
int16_t get_maxStepsToForward () const
uint16_t get_len () const
int8_t get_END_OR_HEADER () const
NetworkMessage ()
NetworkMessage (const NetworkMessage &oldMsg)
NetworkMessage & operator= (const NetworkMessage &oldMsg)
void dec_maxStepsToForward ()
int32_t setUserData (const void *data, uint32_t len)
uint32_t getUserData (void *destination, uint32_t maxLen)
uint32_t numberOfBytesToSend () const
uint16_t calculateCheckSum ()
bool isCheckSumOk ()
void setCheckSum ()
Public Attributes
uint8_t userDataC [MAX_NETWORK_MESSAGE_LENGTH]
local buffer for user data
Private Attributes
uint8_t header [HEADER_SIZE]
Static Private Attributes
static const int HEADER_SIZE = 26
Detailed Description
Simple message data protocol to transmit data to a remote node.
Definition at line 68 of file networkmessage.h.
Constructor & Destructor Documentation
RODOS::NetworkMessage::NetworkMessage () [inline]
Copy constructor and assign operator that only copes nesacary data.
Definition at line 95 of file networkmessage.h.
RODOS::NetworkMessage::NetworkMessage (const NetworkMessage & oldMsg) [inline]
Definition at line 96 of file networkmessage.h.
References memcpy(), and numberOfBytesToSend().
Member Function Documentation
uint16_t RODOS::NetworkMessage::calculateCheckSum () [inline]
Definition at line 131 of file networkmessage.h.
References RODOS::checkSum(), get_len(), header, and HEADER_SIZE.
Referenced by isCheckSumOk(), and setCheckSum().
void RODOS::NetworkMessage::dec_maxStepsToForward () [inline]
Definition at line 102 of file networkmessage.h.
References get_maxStepsToForward(), and put_maxStepsToForward().
uint16_t RODOS::NetworkMessage::get_checksum () const [inline]
Definition at line 81 of file networkmessage.h.
References header.
Referenced by isCheckSumOk().
int8_t RODOS::NetworkMessage::get_END_OR_HEADER () const [inline]
Definition at line 88 of file networkmessage.h.
References header.
uint16_t RODOS::NetworkMessage::get_len () const [inline]
Definition at line 87 of file networkmessage.h.
References header.
Referenced by calculateCheckSum(), getUserData(), and numberOfBytesToSend().
int16_t RODOS::NetworkMessage::get_maxStepsToForward () const [inline]
Definition at line 86 of file networkmessage.h.
References header.
Referenced by dec_maxStepsToForward().
int32_t RODOS::NetworkMessage::get_senderNode () const [inline]
Definition at line 82 of file networkmessage.h.
References header.
uint32_t RODOS::NetworkMessage::get_senderThreadId () const [inline]
Definition at line 84 of file networkmessage.h.
References header.
int64_t RODOS::NetworkMessage::get_sentTime () const [inline]
Definition at line 83 of file networkmessage.h.
References header.
uint32_t RODOS::NetworkMessage::get_topicId () const [inline]
Definition at line 85 of file networkmessage.h.
References header.
uint32_t RODOS::NetworkMessage::getUserData (void * destination, uint32_t maxLen) [inline]
Copies data from message received to a user provided buffer.
Parameters:
destination pointer to output data stream received
length of message buffer, supposed to be <= MAX_NETWORK_MESSAGE_LENGTH
Returns:
length of message copied
Definition at line 123 of file networkmessage.h.
References get_len(), memcpy(), MIN, and userDataC.
bool RODOS::NetworkMessage::isCheckSumOk () [inline]
Definition at line 132 of file networkmessage.h.
References calculateCheckSum(), and get_checksum().
uint32_t RODOS::NetworkMessage::numberOfBytesToSend () const [inline]
Definition at line 130 of file networkmessage.h.
References get_len(), and HEADER_SIZE.
Referenced by NetworkMessage(), and operator=().
NetworkMessage& RODOS::NetworkMessage::operator= (const NetworkMessage & oldMsg) [inline]
Definition at line 97 of file networkmessage.h.
References memcpy(), and numberOfBytesToSend().
void RODOS::NetworkMessage::put_checkSum (uint16_t x) [inline]
Definition at line 72 of file networkmessage.h.
References header.
Referenced by setCheckSum().
void RODOS::NetworkMessage::put_END_OR_HEADER (int8_t x) [inline]
Definition at line 79 of file networkmessage.h.
References header.
void RODOS::NetworkMessage::put_len (uint16_t x) [inline]
Definition at line 78 of file networkmessage.h.
References header.
Referenced by setUserData().
void RODOS::NetworkMessage::put_maxStepsToForward (int16_t x) [inline]
Definition at line 77 of file networkmessage.h.
References header.
Referenced by dec_maxStepsToForward().
void RODOS::NetworkMessage::put_senderNode (int32_t x) [inline]
Definition at line 73 of file networkmessage.h.
References header.
void RODOS::NetworkMessage::put_senderThreadId (uint32_t x) [inline]
Definition at line 75 of file networkmessage.h.
References header.
void RODOS::NetworkMessage::put_sentTime (int64_t x) [inline]
Definition at line 74 of file networkmessage.h.
References header.
void RODOS::NetworkMessage::put_topicId (uint32_t x) [inline]
Definition at line 76 of file networkmessage.h.
References header.
void RODOS::NetworkMessage::setCheckSum () [inline]
Definition at line 133 of file networkmessage.h.
References calculateCheckSum(), and put_checkSum().
int32_t RODOS::NetworkMessage::setUserData (const void * data, uint32_t len) [inline]
Copies user generated data into the message body.
Parameters:
data pointer to input data stream to be transfered
length of message, supposed to be <= MAX_NETWORK_MESSAGE_LENGTH
Returns:
length of message written
Definition at line 110 of file networkmessage.h.
References memcpy(), MIN, put_len(), and userDataC.
Member Data Documentation
uint8_t RODOS::NetworkMessage::header[HEADER_SIZE] [private]
Definition at line 70 of file networkmessage.h.
Referenced by calculateCheckSum(), get_checksum(), get_END_OR_HEADER(), get_len(), get_maxStepsToForward(), get_senderNode(), get_senderThreadId(), get_sentTime(), get_topicId(), put_checkSum(), put_END_OR_HEADER(), put_len(), put_maxStepsToForward(), put_senderNode(), put_senderThreadId(), put_sentTime(), and put_topicId().
const int RODOS::NetworkMessage::HEADER_SIZE = 26 [static, private]
Definition at line 69 of file networkmessage.h.
Referenced by calculateCheckSum(), and numberOfBytesToSend().
uint8_t RODOS::NetworkMessage::userDataC[MAX_NETWORK_MESSAGE_LENGTH]
local buffer for user data
Definition at line 90 of file networkmessage.h.
Referenced by getUserData(), and setUserData().
The documentation for this class was generated from the following file:
/home/sem40wk/workarea/rodos/rodos-113/api/gateway/networkmessage.h