RODOS: RODOS Namespace Reference
RODOS Namespace Reference
Classes
class Application
collection of information about an application.
class CRC
class CommBuffer
A simple buffer for asynchronous communication.
class Fifo
simple FIFO (realized as ring buffer)
class SyncFifo
A synchronized fifo.
class MultipleReaderFifo
class BlockFifo
struct SeenNode
class Gateway
class Linkinterface
struct BufferedCANMessage
class LinkinterfaceCAN
class LinkinterfaceUART
class LinkinterfaceUDP
class NetworkMessage
class TopicListReport
class Router
class TopicReporter
class IOEventReceiver
class GenericIOInterface
class HAL_CAN
class HAL_GPIO
class HAL_I2C
class HAL_PWM
class HAL_SPI
class HAL_UART
class Initiator
Just an interface class to allow an application to initialize before being scheduled.
class ListElement
node of a single linked list
class Putter
Virtual superclass for classes which implement a put function.
class Semaphore
a synchronisation primitive
class NetMsgInfo
class Subscriber
Subscriber to receive messages.
class SubscriberReceiver
class Thread
Thread provides stack and context management
class TimeEvent
Time management
class TimeModel
Time conversion/transformation functions
class TimePoints
Time tagged text
class TopicInterface
TopicInterface only for internal use.
class Topic
Topic to patch publisher and subscribers.
struct GenericMsgRef
class UDPIn
To receive data from a single UDP port (socket) - abstraction layer.
class UDPOut
To send data to a single UPD port (socket) - abstraction layer.
class UDPInOut
class Yprintf
class Ysprintf
Typedefs
typedef ListElement * List
typedef int64_t TTime
WARNING: DEPRECATED, use int64_t.
Enumerations
enum CAN_PARAMETER_TYPE { CAN_PARAMETER_BAUDRATE }
enum CAN_STATUS_TYPE { CAN_STATUS_RX_LEVEL, CAN_STATUS_RX_ERROR, CAN_STATUS_TX_ERROR }
enum CAN_IDX {
CAN_IDX0 = 0, CAN_IDX1, CAN_IDX2, CAN_IDX3,
CAN_IDX4, CAN_IDX5
}
enum GPIO_PIN {
GPIO_000 = 0, GPIO_001, GPIO_002, GPIO_003,
GPIO_004, GPIO_005, GPIO_006, GPIO_007,
GPIO_008, GPIO_009, GPIO_010, GPIO_011,
GPIO_012, GPIO_013, GPIO_014, GPIO_015,
GPIO_016, GPIO_017, GPIO_018, GPIO_019,
GPIO_020, GPIO_021, GPIO_022, GPIO_023,
GPIO_024, GPIO_025, GPIO_026, GPIO_027,
GPIO_028, GPIO_029, GPIO_030, GPIO_031,
GPIO_032, GPIO_033, GPIO_034, GPIO_035,
GPIO_036, GPIO_037, GPIO_038, GPIO_039,
GPIO_040, GPIO_041, GPIO_042, GPIO_043,
GPIO_044, GPIO_045, GPIO_046, GPIO_047,
GPIO_048, GPIO_049, GPIO_050, GPIO_051,
GPIO_052, GPIO_053, GPIO_054, GPIO_055,
GPIO_056, GPIO_057, GPIO_058, GPIO_059,
GPIO_060, GPIO_061, GPIO_062, GPIO_063,
GPIO_064, GPIO_065, GPIO_066, GPIO_067,
GPIO_068, GPIO_069, GPIO_070, GPIO_071,
GPIO_072, GPIO_073, GPIO_074, GPIO_075,
GPIO_076, GPIO_077, GPIO_078, GPIO_079,
GPIO_080, GPIO_081, GPIO_082, GPIO_083,
GPIO_084, GPIO_085, GPIO_086, GPIO_087,
GPIO_088, GPIO_089, GPIO_090, GPIO_091,
GPIO_092, GPIO_093, GPIO_094, GPIO_095,
GPIO_096, GPIO_097, GPIO_098, GPIO_099,
GPIO_100, GPIO_101, GPIO_102, GPIO_103,
GPIO_104, GPIO_105, GPIO_106, GPIO_107,
GPIO_108, GPIO_109, GPIO_110, GPIO_111,
GPIO_112, GPIO_113, GPIO_114, GPIO_115,
GPIO_116, GPIO_117, GPIO_118, GPIO_119,
GPIO_120, GPIO_121, GPIO_122, GPIO_123,
GPIO_124, GPIO_125, GPIO_126, GPIO_127,
GPIO_128, GPIO_129, GPIO_130, GPIO_131,
GPIO_132, GPIO_133, GPIO_134, GPIO_135,
GPIO_136, GPIO_137, GPIO_138, GPIO_139
}
enum GPIO_CFG_TYPE { GPIO_CFG_OUTPUT_ENABLE = 0, GPIO_CFG_NUM_OF_PINS, GPIO_CFG_PULLUP_ENABLE, GPIO_CFG_PULLDOWN_ENABLE }
enum GPIO_IRQ_SENSITIVITY { GPIO_IRQ_SENS_BOTH = 0, GPIO_IRQ_SENS_RISING, GPIO_IRQ_SENS_FALLING }
enum I2C_IDX { I2C_IDX1 = 1, I2C_IDX2, I2C_IDX3, I2C_IDX_MAX }
enum HAL_I2C_ERR {
HAL_I2C_ERR_START = -1, HAL_I2C_ERR_STOP = -2, HAL_I2C_ERR_WRITE = -3, HAL_I2C_ERR_READ = -4,
HAL_I2C_ERR_ADDR = -5, HAL_I2C_ERR_NOT_MASTER = -99
}
enum TIM_CHAN_TypeDef { TIM_CHAN1, TIM_CHAN2, TIM_CHAN3, TIM_CHAN4 }
enum PWM_PARAMETER_TYPE { PWM_PARAMETER_FREQUENCY, PWM_PARAMETER_INCREMENTS }
enum PWM_IDX {
PWM_IDX00 = 0, PWM_IDX01, PWM_IDX02, PWM_IDX03,
PWM_IDX04, PWM_IDX05, PWM_IDX06, PWM_IDX07,
PWM_IDX08, PWM_IDX09, PWM_IDX10, PWM_IDX11,
PWM_IDX12, PWM_IDX13, PWM_IDX14, PWM_IDX15
}
enum SPI_IDX {
SPI_IDX0, SPI_IDX1, SPI_IDX2, SPI_IDX3,
SPI_IDX4, SPI_IDX5, SPI_IDX6
}
enum UART_PARAMETER_TYPE { UART_PARAMETER_BAUDRATE, UART_PARAMETER_HW_FLOW_CONTROL, UART_ENABLE_DMA }
enum UART_STATUS_TYPE { UART_STATUS_RX_BUF_LEVEL, UART_STATUS_RX_ERROR }
enum UART_IDX {
UART_IDX0 = 0, UART_IDX1, UART_IDX2, UART_IDX3,
UART_IDX4, UART_IDX5
}
Functions
short swapShort (short sw_)
long swapLong (long lw_)
long long swapLonglong (long long llw_)
short shortConvertHost2Net (short sw_)
long longConvertHost2Net (long sw_)
long long longlongConvertHost2Net (long long sw_)
uint32_t checkSum (uint8_t *buf, int len)
uint32_t computeCrc (const uint8_t *buf, int32_t len, int32_t initialValue)
uint16_t hash (const char *str)
uint32_t checkSumXor (uint8_t *buf, int len)
char * formatBinary (long val, int len, char *outBuf)
void PRINTF (const char *fmt,...) __attribute__((__format__(__printf__
void void PRINTF_CONDITIONAL (int negligibleLevel, const char *fmt,...) __attribute__((__format__(__printf__
void void void ERROR (const char *text)
void printCharsHex (const char *titel, void *ptr, unsigned int len)
void printCharsHex_Conditional (int negligibleLevel, const char *titel, void *ptr, unsigned int len)
char getcharNoWait ()
bool isCharReady ()
char * getsNoWait ()
void activateTopicCharInput ()
void FFLUSH ()
void prepareNetworkMessage (NetworkMessage &netMsg, const long topicId, const void *data, int len)
class RODOS::NetworkMessage __attribute__ ((packed))
bool getIsHostBigEndian ()
never use before main()
long getSpeedKiloLoopsPerSecond ()
ony an aproximation, max differ +/- 50%
const char * getHostCpuArch ()
const char * getHostBasisOS ()
long getNodeNumber ()
int64_t getNumberOfReceivedMsgsFromNetwork ()
void * xmalloc (long len)
void hwResetAndReboot ()
End of Programm -> reboot Hw deppendent.
void hwInitWatchdog (long intervalMilliseconds)
void hwTriggerWatchdog ()
for CPUS which provide a hardware watchdog
void nop (...)
void schedulerWrapper (long *ctx)
void globalAtomarLock ()
void globalAtomarUnlock ()
int putchar (int c)
void xprintf (const char *fmt,...) __attribute__((__format__(__printf__
void void xsprintf (char *dest, const char *fmt,...)
Variables
bool isHostBigEndian
unsigned long errorCounter
counts how many erros have been detected. Normaly it shall be 0
const char * errorMsg
register the error message of the last Error occured: ist is a uniq pointer too
class RODOS::TopicListReport __attribute__
volatile int64_t idleCnt
a hint about cpu idle time, cnt will be incremented bei idleThread
TimeModel sysTime
Topic< GenericMsgRef > defaultGatewayTopic
Topic< NetworkMessage > defaultRouterTopic
Topic< void * > interruptTimer
Topic< void * > interruptUart
Topic< void * > interruptSigterm
Topic< GenericMsgRef > charInput
used instead of getcharNoWait()
Detailed Description
bigendian is standard net potocoll. Warning: Will be set in main. never use beore main (in static constructurs)
Typedef Documentation
typedef ListElement* RODOS::List
A list is just the pointer to the first element
Definition at line 70 of file listelement.h.
typedef int64_t RODOS::TTime
WARNING: DEPRECATED, use int64_t.
Time represented in the maximal internal time resolution (eg. Nanoseconds, but it could be milliseconds). The Macros SECONDS, MILLISECONDS, etc correspond to this unit
**************** WARNING: Dpereacted, use int64_t
Definition at line 66 of file timemodel.h.
Enumeration Type Documentation
enum RODOS::CAN_IDX
Enumerator:
CAN_IDX0
CAN_IDX1
CAN_IDX2
CAN_IDX3
CAN_IDX4
CAN_IDX5
Definition at line 35 of file hal_can.h.
enum RODOS::CAN_PARAMETER_TYPE
Enumerator:
CAN_PARAMETER_BAUDRATE
Definition at line 22 of file hal_can.h.
enum RODOS::CAN_STATUS_TYPE
Enumerator:
CAN_STATUS_RX_LEVEL
CAN_STATUS_RX_ERROR
CAN_STATUS_TX_ERROR
Definition at line 29 of file hal_can.h.
enum RODOS::GPIO_CFG_TYPE
Enumerator:
GPIO_CFG_OUTPUT_ENABLE
GPIO_CFG_NUM_OF_PINS
GPIO_CFG_PULLUP_ENABLE
GPIO_CFG_PULLDOWN_ENABLE
Definition at line 182 of file hal_gpio.h.
enum RODOS::GPIO_IRQ_SENSITIVITY
Enumerator:
GPIO_IRQ_SENS_BOTH
GPIO_IRQ_SENS_RISING
GPIO_IRQ_SENS_FALLING
Definition at line 192 of file hal_gpio.h.
enum RODOS::GPIO_PIN
Enumerator:
GPIO_000
GPIO_001
GPIO_002
GPIO_003
GPIO_004
GPIO_005
GPIO_006
GPIO_007
GPIO_008
GPIO_009
GPIO_010
GPIO_011
GPIO_012
GPIO_013
GPIO_014
GPIO_015
GPIO_016
GPIO_017
GPIO_018
GPIO_019
GPIO_020
GPIO_021
GPIO_022
GPIO_023
GPIO_024
GPIO_025
GPIO_026
GPIO_027
GPIO_028
GPIO_029
GPIO_030
GPIO_031
GPIO_032
GPIO_033
GPIO_034
GPIO_035
GPIO_036
GPIO_037
GPIO_038
GPIO_039
GPIO_040
GPIO_041
GPIO_042
GPIO_043
GPIO_044
GPIO_045
GPIO_046
GPIO_047
GPIO_048
GPIO_049
GPIO_050
GPIO_051
GPIO_052
GPIO_053
GPIO_054
GPIO_055
GPIO_056
GPIO_057
GPIO_058
GPIO_059
GPIO_060
GPIO_061
GPIO_062
GPIO_063
GPIO_064
GPIO_065
GPIO_066
GPIO_067
GPIO_068
GPIO_069
GPIO_070
GPIO_071
GPIO_072
GPIO_073
GPIO_074
GPIO_075
GPIO_076
GPIO_077
GPIO_078
GPIO_079
GPIO_080
GPIO_081
GPIO_082
GPIO_083
GPIO_084
GPIO_085
GPIO_086
GPIO_087
GPIO_088
GPIO_089
GPIO_090
GPIO_091
GPIO_092
GPIO_093
GPIO_094
GPIO_095
GPIO_096
GPIO_097
GPIO_098
GPIO_099
GPIO_100
GPIO_101
GPIO_102
GPIO_103
GPIO_104
GPIO_105
GPIO_106
GPIO_107
GPIO_108
GPIO_109
GPIO_110
GPIO_111
GPIO_112
GPIO_113
GPIO_114
GPIO_115
GPIO_116
GPIO_117
GPIO_118
GPIO_119
GPIO_120
GPIO_121
GPIO_122
GPIO_123
GPIO_124
GPIO_125
GPIO_126
GPIO_127
GPIO_128
GPIO_129
GPIO_130
GPIO_131
GPIO_132
GPIO_133
GPIO_134
GPIO_135
GPIO_136
GPIO_137
GPIO_138
GPIO_139
Definition at line 23 of file hal_gpio.h.
enum RODOS::HAL_I2C_ERR
Enumerator:
HAL_I2C_ERR_START
HAL_I2C_ERR_STOP
HAL_I2C_ERR_WRITE
HAL_I2C_ERR_READ
HAL_I2C_ERR_ADDR
HAL_I2C_ERR_NOT_MASTER
Definition at line 29 of file hal_i2c.h.
enum RODOS::I2C_IDX
Enumerator:
I2C_IDX1
I2C_IDX2
I2C_IDX3
I2C_IDX_MAX
Definition at line 22 of file hal_i2c.h.
enum RODOS::PWM_IDX
Enumerator:
PWM_IDX00
PWM_IDX01
PWM_IDX02
PWM_IDX03
PWM_IDX04
PWM_IDX05
PWM_IDX06
PWM_IDX07
PWM_IDX08
PWM_IDX09
PWM_IDX10
PWM_IDX11
PWM_IDX12
PWM_IDX13
PWM_IDX14
PWM_IDX15
Definition at line 31 of file hal_pwm.h.
enum RODOS::PWM_PARAMETER_TYPE
Enumerator:
PWM_PARAMETER_FREQUENCY
PWM_PARAMETER_INCREMENTS
Definition at line 26 of file hal_pwm.h.
enum RODOS::SPI_IDX
Enumerator:
SPI_IDX0
SPI_IDX1
SPI_IDX2
SPI_IDX3
SPI_IDX4
SPI_IDX5
SPI_IDX6
Definition at line 18 of file hal_spi.h.
enum RODOS::TIM_CHAN_TypeDef
Enumerator:
TIM_CHAN1
TIM_CHAN2
TIM_CHAN3
TIM_CHAN4
Definition at line 18 of file hal_pwm.h.
enum RODOS::UART_IDX
Enumerator:
UART_IDX0
UART_IDX1
UART_IDX2
UART_IDX3
UART_IDX4
UART_IDX5
Definition at line 40 of file hal_uart.h.
enum RODOS::UART_PARAMETER_TYPE
Enumerator:
UART_PARAMETER_BAUDRATE
UART_PARAMETER_HW_FLOW_CONTROL
UART_ENABLE_DMA
Definition at line 27 of file hal_uart.h.
enum RODOS::UART_STATUS_TYPE
Enumerator:
UART_STATUS_RX_BUF_LEVEL
UART_STATUS_RX_ERROR
Definition at line 35 of file hal_uart.h.
Function Documentation
class RODOS::NetworkMessage RODOS::__attribute__ ((packed))
void RODOS::activateTopicCharInput ()
if you activate the topic cat input, all input string from terminal will be distributed to the topic charInput until you call a getcharNoWait() or getsNoWait();
uint32_t RODOS::checkSum (uint8_t * buf, int len)
Computes a 16 bit checksum (len in bytes) adding bytes and rotating result
Referenced by RODOS::NetworkMessage::calculateCheckSum().
uint32_t RODOS::checkSumXor (uint8_t * buf, int len)
Computes the checkSum of an array of bytes, according to CCSDS algorithm. Warning: There are several checksum standars. See rodos checksum too
uint32_t RODOS::computeCrc (const uint8_t * buf, int32_t len, int32_t initialValue)
computes a 16 bit crc in a non optimized way
void void void RODOS::ERROR (const char * text)
Writes an error text with a leading title to stdout and keeps a counter. Used to report programming errors which shall be corrected.
Referenced by RODOS::Putter::putGeneric(), RODOS::MultipleReaderFifo< Type, len, numOfreaders >::putGeneric(), RODOS::SyncFifo< Type, len >::putGeneric(), RODOS::Fifo< NetworkMessage, 1500 >::putGeneric(), RODOS::CommBuffer< Type >::putGeneric(), RODOS::Subscriber::~Subscriber(), RODOS::Topic< GenericMsgRef >::~Topic(), and RODOS::TopicInterface::~TopicInterface().
void RODOS::FFLUSH ()
Like in linux fflush(stdout)
char* RODOS::formatBinary (long val, int len, char * outBuf)
Writes 0 terminated 1/0 string representing the input value, takes the lower 'len' bits warning: it writes in outbuf 'len' bytes + a terminating 0 (len +1)
Parameters:
[in] val 4-byte to be represented as list of bits
[in] len number of bits used within val
in/out] outBuf buffer to write string
Returns:
outBuf buffer to write string
char RODOS::getcharNoWait ()
Function to read a character from stream, in case one has been written. Normal getchar (in linux) will stop the complete execution. In order to avoid waiting first isCharRaedy() is called. The implemetation is platform dependend defined in getcharnowait.cpp.
Returns:
latest character read, -1 if no character is available
const char* RODOS::getHostBasisOS ()
const char* RODOS::getHostCpuArch ()
bool RODOS::getIsHostBigEndian ()
never use before main()
long RODOS::getNodeNumber ()
if a network and a gateway are present, my node number
int64_t RODOS::getNumberOfReceivedMsgsFromNetwork ()
char* RODOS::getsNoWait ()
Get a string using getcharNoWait(). Returns If a string is ready it returns a pointer to it, else it returns 0 (no wait). The maximal length of a string is 120 chars (due to internal buffers). The String will not be modified until the next call to getsNoWait. Not Thread save. Only one reader from stdin is allowed. Else... I dont know, try what it does and let me know.
long RODOS::getSpeedKiloLoopsPerSecond ()
ony an aproximation, max differ +/- 50%
void RODOS::globalAtomarLock ()
usualy you can create short atomar sections using the macro PRIOTIRY_CEILING which is the standard, recomended procedure.
But some applications demand enableing and disabling the scheduling process. for thos aplications we use globalAtomarLock and globalAromarUnlock
WARNING!!!: Deprecated avoid it! (no implementation on posix derivates) In multicore processors it does not help!
void RODOS::globalAtomarUnlock ()
uint16_t RODOS::hash (const char * str)
Delivers a 16 bit hash value for a string. both bytes contain only printable characters
void RODOS::hwInitWatchdog (long intervalMilliseconds)
void RODOS::hwResetAndReboot ()
End of Programm -> reboot Hw deppendent.
void RODOS::hwTriggerWatchdog ()
for CPUS which provide a hardware watchdog
bool RODOS::isCharReady ()
Checks if a new character has been received from stdin. Associated to getcharNoWait(). Returns true if a new character is available in order to read it with getcharNoWait.
Returns:
1 if a new character is in the buffer, 0 otherwise
long RODOS::longConvertHost2Net (long sw_)
long long RODOS::longlongConvertHost2Net (long long sw_)
void RODOS::nop (...)
Nop... no operation ... do nothing
void RODOS::prepareNetworkMessage (NetworkMessage & netMsg, const long topicId, const void * data, int len)
void RODOS::printCharsHex (const char * titel, void * ptr, unsigned int len)
Print a character bitwise, highest bit first. obsolete! use b in PRINTF
Parameters:
[in] val 8-bit value to be printed Prints an array of bytes as hex values
[in] titel leading text in the line printed before values
[in] ptr pointer to array to be printed as unsigned char
[in] len number of characters, respectively bytes in the array
void RODOS::printCharsHex_Conditional (int negligibleLevel, const char * titel, void * ptr, unsigned int len)
void RODOS::PRINTF (const char * fmt, ...)
Printf protected with a semaphore: Thread safe Warinig: 3.9f means 3 digits then . then 9 digits
void void RODOS::PRINTF_CONDITIONAL (int negligibleLevel, const char * fmt, ...)
prints only if negligibleLevel <= printfVerbosity, Important msgs have lower negligibleLevel
int RODOS::putchar (int c)
micro printf (subset)
Autor: Unkown (long long time ago) c++, ll, b: Extended: Sergio Montenegro, 2011 f : Sergio Montenegro, 2012 Warning: 3.9f means 3 postions, then . then 9 positions
Referenced by RODOS::Yprintf::yputc().
void RODOS::schedulerWrapper (long * ctx)
short RODOS::shortConvertHost2Net (short sw_)
long RODOS::swapLong (long lw_)
long long RODOS::swapLonglong (long long llw_)
short RODOS::swapShort (short sw_)
void* RODOS::xmalloc (long len)
allocation of memory. no free of mem exists. allocates static memory. it shall not be unset after thread:run() begin
void RODOS::xprintf (const char * fmt, ...)
void void RODOS::xsprintf (char * dest, const char * fmt, ...)
Variable Documentation
class RODOS::TopicListReport RODOS::__attribute__
Topic<GenericMsgRef> RODOS::charInput
used instead of getcharNoWait()
Topic<GenericMsgRef> RODOS::defaultGatewayTopic
A topic only for gateways
Topic<NetworkMessage> RODOS::defaultRouterTopic
unsigned long RODOS::errorCounter
counts how many erros have been detected. Normaly it shall be 0
const char* RODOS::errorMsg
register the error message of the last Error occured: ist is a uniq pointer too
volatile int64_t RODOS::idleCnt
a hint about cpu idle time, cnt will be incremented bei idleThread
Topic<void*> RODOS::interruptSigterm
Topic<void*> RODOS::interruptTimer
Topic<void*> RODOS::interruptUart
bool RODOS::isHostBigEndian
bigendian is standard net potocoll. Warning: Will be set in main. never use beore main (in static constructurs)
TimeModel RODOS::sysTime
A global time object