RODOS: /home/sem40wk/workarea/rodos/rodos-113/api/string_pico.h File Reference
/home/sem40wk/workarea/rodos/rodos-113/api/string_pico.h File Reference
#include <stddef.h>
Defines
#define bcopy(src, dest, n) memcpy(dest, src, n)
#define bzero(dest, len) memset(dest, 0, len)
Functions
size_t strlen (const char *s)
size_t strnlen (const char *s, size_t n)
char * strcpy (char *dest, const char *s)
char * strncpy (char *dest, const char *src, size_t n)
void * memcpy (void *dest, const void *s, size_t len)
void * memset (void *dest, int val, size_t len)
int strcmp (char const *a, char const *b)
int strncmp (char const *a, char const *b, size_t n)
Define Documentation
#define bcopy (src, dest, n) memcpy(dest, src, n)
Definition at line 27 of file string_pico.h.
#define bzero (dest, len) memset(dest, 0, len)
Definition at line 28 of file string_pico.h.
Function Documentation
void* memcpy (void * dest, const void * s, size_t len)
Referenced by RODOS::NetworkMessage::getUserData(), RODOS::NetworkMessage::NetworkMessage(), RODOS::NetworkMessage::operator=(), and RODOS::NetworkMessage::setUserData().
void* memset (void * dest, int val, size_t len)
int strcmp (char const * a, char const * b)
char* strcpy (char * dest, const char * s)
size_t strlen (const char * s)
int strncmp (char const * a, char const * b, size_t n)
char* strncpy (char * dest, const char * src, size_t n)
size_t strnlen (const char * s, size_t n)