#! /bin/bash



if [ -z $RODOS_ROOT ]; then
source `dirname $0`/print_no_envs_warning
fi

source ${RODOS_MAKES}/avr32-set-vars


############ frome here: generic-lib
cd ${RODOS_LIBS}

\rm -rf ${ARCH}
mkdir   ${ARCH}


### compile hw-independent sources ###
${CPP_COMP} ${CFLAGS}  ${CPPFLAGS} ${INCLUDES}  ${RODOS_ROOT}/src/independent/*.cpp  -c
${CPP_COMP} ${CFLAGS}  ${CPPFLAGS} ${INCLUDES}  ${RODOS_ROOT}/src/independent/gateway/*.cpp  -c
${CPP_COMP} ${CFLAGS}  ${CPPFLAGS} ${INCLUDES}  ${MY_SRCS}/*.cpp  -c

#${CPP_COMP} ${CFLAGS}  ${CPPFLAGS} ${INCLUDES}  ${RODOS_SUPPORT_LIBS}/*.cpp  -c


### compile hw-dependent sources ###
#${C_COMP}  ${CFLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/avr32_hal/*.c
${C_COMP}  ${CFLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/avr32_framework/*.c
${C_COMP}  ${CFLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/avr32_framework/startup/*.c
#${C_COMP}  ${CFLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/*.c

${CPP_COMP}  ${CFLAGS} ${CPPFLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/hal/*.cpp
#${CPP_COMP}  ${CFLAGS} ${CPPFLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/avr32_framework/*.cpp
${CPP_COMP}  ${CFLAGS} ${CPPFLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/*.cpp

#${C_COMP}   ${HWCFLAGS} ${ASM_FLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/avr32_hal/*.c
${C_COMP}  ${HWCFLAGS} ${ASM_FLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/avr32_framework/*.S
${C_COMP}  ${HWCFLAGS} ${ASM_FLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/avr32_framework/startup/*.S
${C_COMP}  ${HWCFLAGS} ${ASM_FLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/*.S


ar rc librodos.a *.o
mv librodos.a ${ARCH}
\rm -f *.o

source ${RODOS_MAKES}/check_rodos_support
echo ""
echo "Building support-libs ..."
cd ${RODOS_SUPPORT_LIBS}
source doit-avr32

cd ${RODOS_ROOT}

