#!/bin/bash

#************************************************************************
# Script that creates the environment for the Cross Compilation 
#************************************************************************
source ${RODOS_MAKES}/console_colors
echo $GREEN_BOLD"----- SETTING RODOS FOR Cortex A8 -----"

# If $RODOS_ROOT is a empty string, print an error
if [ -z $RODOS_ROOT ]; then
source `dirname $0`/print_no_envs_warning $1
fi  

echo $BLUE_BOLD"      -> Setting environment"
source ${RODOS_MAKES}/cortexa8-set-vars


# Move to directory /libs
cd ${RODOS_LIBS}
# Remore actual directory and create a new one
\rm -rf ${ARCH}
mkdir   ${ARCH}

# Print no informatin
PRINTF_INFO=0


echo $BLUE_BOLD"      -> Compiling files for:" ${DIRECTORY_FLAG}
# Board independent files **#
echo $CYAN_BOLD"           rodos/src/independent/"
${CXX_COMP} ${CXX_FLAGS} ${INCLUDES} -c ${RODOS_ROOT}/src/independent/*.cpp
echo "           rodos/src/independent/gateway/"
${CXX_COMP} ${CXX_FLAGS} ${INCLUDES} -c ${RODOS_ROOT}/src/independent/gateway/*.cpp
echo "           rodos/src/bare-metal-generic/"
${CXX_COMP} ${CXX_FLAGS} ${INCLUDES} -c ${MY_SRCS}/*.cpp
#***************************#

# Board dependent files ****#
echo "           rodos/src/bare-metal/arm-cortexA8/"
${CXX_COMP} ${CXX_FLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/*.cpp
${CXX_COMP} ${CXX_FLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/hal/*.cpp
${CXX_COMP}  ${CXX_FLAGS}   ${INCLUDES} -c ${MY_HW_SRCS}/*.c
${CXX_COMP} ${ASM_FLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/*.S

echo "           rodos/src/bare-metal/arm-cortexA8/drivers/"
#${CXX_COMP} ${CXX_FLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/drivers/*.cpp
${CXX_COMP} ${CXX_FLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/drivers/*.c
#${CXX_COMP} ${ASM_FLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/src/core/*.S

echo "           rodos/src/bare-metal/arm-cortexA8/platform/beaglebone"
${CXX_COMP} ${CXX_FLAGS} ${INCLUDES} -c ${MY_HW_SRCS}/platform/beaglebone/*.c


#***************************#

# Rodos library ************#
#echo "           rodos/support_libs/"
#${CXX_COMP} ${CXX_FLAGS} ${INCLUDES} -c ${RODOS_SUPPORT_LIBS}/*.cpp	
#***************************#

# Archive and delete .o ****#
ar rc librodos.a *.o
mv librodos.a ${ARCH}/${DIRECTORY_FLAG}
\rm -f *.o
#***************************#


cd ${RODOS_ROOT}

echo $GREEN_BOLD"----- RODOS FOR Cortex A8 DONE -----"$RESET
