#!/bin/sh
# Check whether environment has been set
if [ -z $RODOS_ROOT ]; then
   # Environment is not set
   source `dirname $0`/print_no_envs_warning
fi  


echo "********************************************"
echo "*** compiling all sources, just to check"
echo "*** to compile one specially see doit"
echo "********************************************"
echo
for i in  *.cpp
do
  echo $i
  freertos-executable $i
done

