#!/bin/bash
if [ -z $RODOS_ROOT ]; then
source `dirname $0`/print_no_envs_warning
fi

# Create project directory
if [ -d "iMX6" ]; then
	\rm -rf iMX6/cpu1
	mkdir iMX6/cpu1
else
	mkdir iMX6
	# Create sub-directory for current CPU ID
	mkdir iMX6/cpu1
fi

# Setting environment
source ${RODOS_MAKES}/iMX6-set-vars
source ${RODOS_MAKES}/console_colors

# Compile target file ******#
echo $GREEN_BOLD"Compiling target file for cpu1:" $*
${CXX_COMP} ${CPU_FLAG} ${CXX_FLAGS} -DCPU1 ${INCLUDES} -c $*
#***************************#	

# Linking file *************#
echo $BLUE_BOLD"Linking target file:            "$*" -> cpu1.elf"
${CXX_COMP} -T${CPU1_SCRIPT} ${LINKER_OPTIONS} -L${LINKER_LIB_PATH} -o cpu1.elf *.o ${LINKER_LIB_INC}
#***************************#

# Converting the image *****#
echo $RED_BOLD"Converting:                     cpu1.elf -> cpu1.bin (binary) " $RESET
${OBJCOPY} -O binary cpu1.elf cpu1.bin
#***************************#

# Move compiled files ******#
mv *.o *.elf *.bin iMX6/cpu1
\rm -f *.o *.elf *.bin
#***************************#
