#! /bin/bash 

#set -euC
shopt -s nullglob

if [ -z "$RODOS_ROOT" ]; then
  source "`dirname $0`/print_no_envs_warning"
fi

source ${RODOS_MAKES}/leon2-vars-envs-spwrtc

OUT=${OUT-tst}

# fuer dem VHDL SImulator 
#${CPP_COMP} -o ${OUT}-sim "$@" \
#    ${CXXFLAGS} ${MORE_CFLAGS-} ${INCLUDES} \
#    ${LINKFLAGS_SIM}

${CPP_COMP} -o ${OUT} "$@" \
    ${CXXFLAGS} ${MORE_CFLAGS-} ${INCLUDES} \
    ${LINKFLAGS}
