#!/bin/bash
# author: Andre Bartke <dev@bartke.cc>

# do not print error if wildcards are not found
shopt -s nullglob

# check environment
if [ -z "${RODOS_ROOT}" ]; then
  source "`dirname $0`/print_no_envs_warning"
fi

source "${RODOS_MAKES}/ppc405-qemu-set-vars"

TERM=xterm
QEMU_BIN=`which qemu-system-ppc`
GDB=powerpc-linux-gdb

## first we have to create the iso image

if [ ! -e tst ] ; then
  echo "Error: tst not found."
  echo "first call ppc405-qemu-executable yourfile.cpp"
  exit
fi

## choose an emulator and run it

if [ "$QEMU_BIN" != "" ]; then
  echo ""
  echo "-- Choose emulator"

  while true; do
    echo "  [1] QEMU"
    echo "  [2] QEMU+GDB Remote Debugging"
    echo "  [a] abort"
    read -p "[1|2|a] " select

    case $select in
      [1] )
        $QEMU_BIN -M taihu -cpu 51210950 -kernel tst -bios $RODOS_ARCH_DST/ppc405_rom.bin -nographic
    break;;
      [2] )
        ELF_PATH=`pwd`
        $TERM -e "$QEMU_BIN -M taihu -cpu 51210950 -kernel tst -bios $RODOS_ARCH_DST/ppc405_rom.bin -nographic -S -s" &
        sleep 1 # wait for qemu to startup
        $TERM -e "$GDB_PATH -ex 'target remote localhost:1234' -ex 'symbol $ELF_PATH/tst.elf'" &
    break;;
      [aA] )
        exit;;
    esac
  done

else
  echo "Error: No emulator found, please install QEMU."
fi

