#! /bin/bash

shopt -s nullglob

if [ -z "$RODOS_ROOT" ]; then
  source "`dirname $0`/print_no_envs_warning"
fi

source "${RODOS_MAKES}/ppc405-xc4vfx60-set-vars"

if [ -f ./tst ]; then
	echo "tst: OK"
#	rm *.hex &> /dev/null
	xmd -tcl "$RODOS_ARCH_SRC/boot/bsp-${BSP}/load_system.tcl" "./tst"
else
	echo "tst: FAIL"
	exit 1;
fi


