#! /bin/bash

if [ -z $RODOS_ROOT ]; then
source `dirname $0`/print_no_envs_warning
fi  

source ${RODOS_MAKES}/raspberrypi-set-vars

rm -f *.d
rm -f *.o
rm -f *.elf
rm -f *.list

${CXX} ${CFLAGS} ${CPPFLAGS} ${INCLUDES} -c $* 
${CXX} ${HWCFLAGS} -o rpi.elf *.o ${RODOS_LIBS}/${ARCH}/build/*.o ${LINKFLAGS}
${OBJDUMP} -D rpi.elf > rpi.list
${OBJCOPY} rpi.elf -O binary kernel.img

rm -f *.o

