#!/bin/bash

if [ -z $RODOS_ROOT ]; then
source `dirname $0`/print_no_envs_warning
fi

source ${RODOS_MAKES}/raspberrypi-set-vars

cd ${RODOS_LIBS}

# create lib/raspberrypi
rm -rf ${ARCH}
mkdir -p  ${ARCH} && cd ${ARCH}
pushd . > /dev/null

# create lib/raspberrypi/build
mkdir -p  build && cd build

# compile RODOS hw-independent files
${CXX} ${CFLAGS}  ${CPPFLAGS} ${INCLUDES}  ${RODOS_SRC1}/*.cpp  -c
${CXX} ${CFLAGS}  ${CPPFLAGS} ${INCLUDES}  ${RODOS_SRC2}/*.cpp  -c
${CXX} ${CFLAGS}  ${CPPFLAGS} ${INCLUDES}  ${RODOS_SRC3}/*.cpp  -c
#${CXX} ${CFLAGS}  ${CPPFLAGS} ${INCLUDES}  ${RODOS_SUPPORT_LIBS}/*.cpp  -c

# compile hw-dependent files
${CC}  ${CFLAGS} ${INCLUDES} ${RODOS_ARCH_SRC1}/startup/{*.S,*.c} -c
${CXX} ${CFLAGS} ${CPPFLAGS} ${INCLUDES} ${RODOS_ARCH_SRC1}/*.cpp -c
${CXX} ${CFLAGS} ${CPPFLAGS} ${INCLUDES} ${RODOS_ARCH_SRC1}/hal/*.cpp -c

popd > /dev/null

${AR} -rc librodos.a build/*.o

#mv librodos.a ${ARCH}
#\rm -f *.o

# compile support libs
source ${RODOS_MAKES}/check_rodos_support
echo ""
echo "Building support-libs ..."
cd ${RODOS_SUPPORT_LIBS}
source doit-raspberrypi

cd ${RODOS_ROOT}

