#! /bin/bash

# written by Andre Bartke <dev@bartke.cc>
# Adapted from linux/leon2/ocn versions.

shopt -s nullglob

if [ -z "$RODOS_ROOT" ]; then
  source "`dirname $0`/print_no_envs_warning"
fi

source "${RODOS_MAKES}/sparc64-set-vars"

#echo ""
#echo "-- Creating kernel image"
#echo " Applications: ${@%.*}"
${CXX} ${CXXFLAGS} ${INCLUDES} -o tst $@ ${CXX_LINKER_FLAGS} || exit
#echo "...done."
