#! /bin/bash



if [ -z $RODOS_ROOT ]; then
source `dirname $0`/print_no_envs_warning
fi

source ${RODOS_MAKES}/stm32-set-vars

echo ${DENSITY_WARNING} 

############ frome here: generic-lib
cd ${RODOS_LIBS}

\rm -rf ${ARCH}
mkdir   ${ARCH}


${CPP_COMP} ${CFLAGS}  ${CPPFLAGS} ${INCLUDES}  ${RODOS_ROOT}/src/independent/*.cpp  -c
${CPP_COMP} ${CFLAGS}  ${CPPFLAGS} ${INCLUDES}  ${RODOS_ROOT}/src/independent/gateway/*.cpp  -c
${CPP_COMP} ${CFLAGS}  ${CPPFLAGS} ${INCLUDES}  ${MY_SRCS}/*.cpp  -c
#${CPP_COMP} ${CFLAGS}  ${CPPFLAGS} ${INCLUDES}  ${RODOS_SUPPORT_LIBS}/*.cpp  -c


${C_COMP}   ${HWCFLAGS} ${CFLAGS_BASICS} ${INCLUDES} -c ${MY_HW_SRCS}/stm32/*.c
${C_COMP}   ${HWCFLAGS} ${CFLAGS_BASICS} ${INCLUDES} -c ${MY_HW_SRCS}/*.c
${CPP_COMP} ${HWCFLAGS} ${CFLAGS_BASICS} ${CPPFLAGS} ${INCLUDES} -c  ${MY_HW_SRCS}/*.cpp
${CPP_COMP} ${HWCFLAGS} ${CFLAGS_BASICS} ${CPPFLAGS} ${INCLUDES} -c  ${MY_HW_SRCS}/hal/*.cpp

#mv   00globalobjects.o ${ARCH}  #  >& /dev/null
ar rc librodos.a *.o
mv librodos.a ${ARCH}
\rm -f *.o

source ${RODOS_MAKES}/check_rodos_support

cd ${RODOS_ROOT}

