#! /bin/bash

if [ -z $RODOS_ROOT ]; then
source `dirname $0`/print_no_envs_warning
fi  

source ${RODOS_MAKES}/freertos-stm32f4-set-vars

\rm -f *.d
\rm -f *.o

${CPP_COMP} ${CFLAGS} ${CPPFLAGS} ${INCLUDES} -c $* 
${C_COMP} ${HWCFLAGS} ${FIRST_LINK_OBJ} -o stm32f4.elf *.o ${LINKFLAGS} 

rm -f *.o


