#! /bin/bash -x

# Copyright: DLR
# Author:    Steffen Wiegratz, Henrik Theiling, AbsInt Angewandte Informatik GmbH
# Adapted from linux and arm versions.

# Include with source, otherwise setting variables has no effect.

export ARCH=arch_virtex4

## Directory structure:
export RODOS_SRC1="${RODOS_ROOT}/src/independent"
export RODOS_SRC2="${RODOS_ROOT}/src/on-posix-virtex4"
export RODOS_SRC3="${RODOS_SRC1}/gateway"
export RODOS_PRINTF_SRC="${RODOS_ROOT}/src/independent/printf"
export RODOS_ARCH_DST="${RODOS_LIBS}/${ARCH}"

## Compiler settings:
export RODOS_GCC_PREFIX="${RODOS_GCC_PREFIX_VIRTEX4-/opt/Xilinx/12.3/ISE_DS/EDK/gnu/powerpc-eabi/lin/bin/powerpc-eabi}"

if test -z "`basename \"${RODOS_GCC_PREFIX}\"`"
then
  export RODOS_GCC_PREFIX_="${RODOS_GCC_PREFIX}"
else
  export RODOS_GCC_PREFIX_="${RODOS_GCC_PREFIX}-"
fi

export RODOS_GCC_BIN="`dirname \"${RODOS_GCC_PREFIX}\"`"

PATH="${RODOS_GCC_BIN}:${PATH}"

export HARDWARE=""

#export CXXFLAGS_ONLY=" -fno-rtti -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables "
export CXXFLAGS_ONLY=" -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables "
export CFLAGS_BASICS=" -fno-exceptions -W -Wall -Wextra -Wno-unused-parameter -Wundef -Os "
#export HWCFLAGS=" ${HARDWARE} -Dprivate=public -Dprotected=public -D __XMK__ -I/home/user/xilinx_sdkworkspace/xilkernel_bsp_0/ppc405_0/include"
export HWCFLAGS=" ${HARDWARE} -D __XMK__ -I/home/user/xilinx_sdkworkspace/xilkernel_bsp_1/ppc405_0/include"

export OS_COMPONENTS="src src/printf hw_dependent/${ARCH}"
# What will go into librodos.a.
# generic.make will gather all .c, .cpp, .s, and .S files from these directories.

export INCLUDES=" 	-I${RODOS_SRC1} \
			-I${RODOS_SRC2} \
			-I${RODOS_SRC3} \
			-I${RODOS_API}  \
                        -I${RODOS_SUPPORT_LIBS} \
			${APP_INCLUDES}"

# HT: Include order changed because of redundant (and probably
#     wrong) hw_specific.h file in src/.  The copy for ARM is
#     different.  The copy for VIRTEX4 is thought to be the most
#     generic and correct one, so we want to find it before
#     anything else.

export CFLAGS=" ${CFLAGS_BASICS} ${HWCFLAGS} "
export CXXFLAGS=" ${CFLAGS} ${CXXFLAGS_ONLY} "

# FIXME: I don't understand the distinction yet, why 00globalobjects and crl are
# special in the ARM port.
# export FIRST_LINK_OBJ=" ${RODOS_LIBS}/${ARCH}/00globalobjects.o "

#export LINKFLAGS=" -Wl,--script=/home/user/xilinx_sdkworkspace/hello_world_0/src/lscript.ld -L ${RODOS_LIBS}/${ARCH} -lrodos -lxil -lxilkernel -lsyscall -lm -lgcc "
export LINKFLAGS=" -Wl,--script=${RODOS_SRC2}/lscript.ld -L ${RODOS_LIBS}/${ARCH} -lrodos -lxil -lxilkernel -lsyscall -lm -lgcc "


export CPP_COMP="${RODOS_GCC_PREFIX_}g++"
export C_COMP="${RODOS_GCC_PREFIX_}gcc"
export AR_EXE="${RODOS_GCC_PREFIX_}ar"
export RANLIB_EXE="${RODOS_GCC_PREFIX_}ranlib"
export OBJCOPY_EXE="${RODOS_GCC_PREFIX_}objcopy"
export OBJDUMP_EXE="${RODOS_GCC_PREFIX_}objdump"
export MKPROM_EXE="${RODOS_GCC_BIN}/../mkprom2/mkprom2"

