project(${PROJECT_NAME})

IF(UNIX)
	IF(CYGWIN)
		include(posix)
	ELSE()
		include(linux_x86)
	ENDIF()
ELSEIF(WIN32)
	IF (MSVC)
		include(windows)
	ELSE()
		ADD_DEFINITIONS(-m32 -O2 -fno-exceptions -mfpmath=387 -c)
		include(windows)
	ENDIF()
ELSE()
	MESSAGE(FATAL_ERROR "No build for this architecture available!")
ENDIF()
